services:

  api_endpoint_1:
    image: api_endpoint_1:dev
    container_name: api_endpoint_1
    build:
      dockerfile: endpoint_1/Dockerfile
    command: uvicorn endpoint_1.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
    env_file:
      - endpoint_1/.env
    depends_on:
      - db_postgres_1
      - redis_data_store
      - rabbitmq_infra

  api_endpoint_2:
    image: api_endpoint_2:dev
    container_name: api_endpoint_2
    build:
      dockerfile: endpoint_2/Dockerfile
    command: uvicorn endpoint_2.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - .:/usr/src/app
    ports:
      - 8002:8001
    env_file:
      - endpoint_2/.env
    depends_on:
      - db_postgres_2
      - redis_data_store

  redis_data_store:
    image: redis:6.2.5-alpine
    container_name: redis_data_store
    # network_mode: host
    ports:
      - 6379:6379

  db_postgres_1:
    image: postgres:16.1
    container_name: db_postgres_1
    env_file:
      - postgres_db_1/.env
    volumes:
      - postgres-db1:/var/lib/postgresql/data
    ports:
        - 5432:5432

  db_postgres_2:
    image: postgres:16.1
    container_name: db_postgres_2
    env_file:
      - postgres_db_2/.env
    volumes:
      - postgres-db2:/var/lib/postgresql/data
    ports:
        - 5433:5432

  rabbitmq_infra:
    image: rabbitmq-delayed-message-exchange:dev
    build:
      dockerfile: rabbitmq_infra/Dockerfile
    container_name: rabbitmq_infra
    env_file:
      - rabbitmq_infra/.env
    ports:
      - "5672:5672"
      - "15672:15672"

  queue_consumer:
    image: queue_consumer:dev
    container_name: queue_consumer
    env_file:
      - queue_consumer/.env
    build:
      dockerfile: queue_consumer/Dockerfile
    command: 'python -u main.py'
    depends_on:
      - rabbitmq_infra

volumes:
  postgres-db1:
    name: db_postgres_1
  postgres-db2:
    name: db_postgres_2
