
INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto A', 50, current_timestamp, '1');
INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto B', 100, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto C', 150, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto D', 200, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto E', 250, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto F', 300, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto G', 350, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto H', 400, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto I', 450, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto J', 500, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto L', 50, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto M', 100, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto N', 150, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto O', 200, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto P', 250, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto Q', 300, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto R', 350, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto S', 400, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto T', 450, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto U', 500, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto V', 50, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto X', 100, current_timestamp, '1');
-- INSERT INTO public.orders(id, product, price, created_at, security_check)VALUES(nextval('orders_id_seq'::regclass), 'Produto Z', 150, current_timestamp, '1');
commit;
