
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto A', 50);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto B', 100);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto C', 150);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto D', 200);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto E', 250);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto F', 300);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto G', 350);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto H', 400);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto I', 450);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto J', 500);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto L', 50);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto M', 100);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto N', 150);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto O', 200);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto P', 250);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto Q', 300);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto R', 350);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto S', 400);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto T', 450);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto U', 500);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto V', 50);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto X', 100);
INSERT INTO public.orders(id, description, quantity)VALUES(nextval('orders_id_seq'::regclass), 'Produto Z', 150);
commit;
